server:
  port: 9001
spring:
  cloud:
    gateway:
      httpserver:
        wiretap: true
      httpclient:
        wiretap: true
        response-timeout: 120s
        proxy:
          host: velodrome.usefixie.com
          port: 80
          username: fixie
          password: ${FIXIE_PASSWORD}
      routes:
        - id: sanef
          uri: http://35.231.60.190
          predicates:
            - Path=/sanef_api_thirdparty/**
        - id: zenith
          uri: ${ZENITH_HOST}
          predicates:
            - Path=/AgencyBankingService/**
        - id: unity
          uri: ${UNITY_HOST}
          predicates:
            - Path=/api/**
management:
  endpoints:
    web:
      exposure:
        include: env, health, gateway, info, metrics